#!/bin/sh
set -e

PREREQS=""
case $1 in
    prereqs) echo "${PREREQS}"; exit 0;;
esac

. /usr/share/initramfs-tools/hook-functions

FW_LIST="qcom/sdm845/OnePlus/enchilada/a630_zap.mbn \
         qcom/sdm845/OnePlus/enchilada/adsp.mbn \
         qcom/sdm845/OnePlus/enchilada/cdsp.mbn \
         qcom/sdm845/OnePlus/enchilada/ipa_fws.mbn \
         qcom/sdm845/OnePlus/enchilada/slpi.mbn \
         qcom/a630_sqe.fw \
         qcom/a630_gmu.bin"

add_firmware ${FW_LIST}

